### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by linyini2** [delta-mpc/python-psi#1]
I am new to PSI(private set intersection) and I have some troubles in running the codes. 
I wonder why I get an error when I run the command : `python psi_server.py`

The error: **ConnectionRefusedError: [WinError 10061]**

I have tried to **Change the native proxy Settings to auto-detect Settings**, but it doesn't work.

**Comment by mh739025250** [comment]
I never test my code on windows system, and this error doesn't occur on Linux.
Can you show the stack trace of the error, or test the code on Linux?

**Comment by mrdutq** [comment]
I also encountered the same problem, in Win10 the problem is "**ConnectionRefusedError: [WinError 10061]**", in Ubuntu 20.04 the error is "**ConnectionRefusedError : [Errno 111] Connection refused**" . Have you solved this problem? How did you solve it?

**Comment by linyini2** [comment]
I later tried to git clone this project again(win 10, python 3.7), and it turned out to be successful. So I guess there is something wrong with the network.

**Comment by linyini2** [comment]
> I also encountered the same problem, in Win10 the problem is "**ConnectionRefusedError: [WinError 10061]**", in Ubuntu 20.04 the error is "**ConnectionRefusedError : [Errno 111] Connection refused**" . Have you solved this problem? How did you solve it?

I later tried to git clone this project again(win 10, python 3.7), and it turned out to be successful. So I guess there is something wrong with the network.
