### ISSUE TITLE
为什么运行 显示不可识别呢？

### ISSUE THREAD

**Issue by wywywyyyy** [delta-mpc/python-psi#14]
![4a973827cb84a5e105b98ef285e0844](https://user-images.githubusercontent.com/107463551/208300198-14e6ef0d-16b0-461d-9c16-b3f3c3b986e9.png)

**Comment by wywywyyyy** [comment]
python是3.9.8版本，操作系统是windows
尝试直接运行psi_run server 127.0.0.1:2345 和psi_run client 127.0.0.1:1234 可以跑起来 但是二者连接不上
![image](https://user-images.githubusercontent.com/107463551/208300495-b7c41302-1222-4172-a091-cadfe5865cf8.png)
![image](https://user-images.githubusercontent.com/107463551/208300522-8ba7cd2b-5070-4c40-8849-41c9dd6958cc.png)

**Comment by liuyanntes** [comment]
windows无法运行，需要服务器；然鹅Linux同样会报错，见：https://github.com/delta-mpc/python-psi/issues/12

**Comment by liuyanntes** [comment]
同志们，解决了！

**Comment by liuyanntes** [comment]
你需要一台Linux服务器，安装好python3，安装好所需依赖
关键：开启两个Shell窗口
一个作为server执行：PSI_CONFIG=config/server.config.yaml psi_run server 127.0.0.1:2345
一个作为client执行：PSI_CONFIG=config/client.config.yaml psi_run client 127.0.0.1:1234

注意：两条命令不能间隔太久，否则会报错超时
