### ISSUE TITLE
PSI_CONFIG=config/config.yaml : 无法将“PSI_CONFIG=config/config.yaml”项识别为 cmdlet、函数、脚本文件或可运行程序的名 称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。

### ISSUE THREAD

**Issue by TediousBoredom** [delta-mpc/python-psi#17]
<img width="844" alt="image" src="https://github.com/delta-mpc/python-psi/assets/111668189/632e87d7-9eec-4ec3-92db-91b5c8d43e18">
<img width="867" alt="error" src="https://github.com/delta-mpc/python-psi/assets/111668189/b71d1def-60df-4c43-b352-71bec6d11498">
无法启动PSI服务端和客户端

**Comment by lencyforce** [comment]
这个指定环境变量的方式是Linux的命令，Windows下不是这样写的
