### ISSUE TITLE
跑不起来？

### ISSUE THREAD

**Issue by leftlefthand** [delta-mpc/python-psi#4]
python setup.py install时报需要安装numpy 1.20.2版本，换了各种源都搜不该版本，后来查了官网最新R版才1.20.0，请问怎么才能运行？

**Comment by mh739025250** [comment]
![image](https://user-images.githubusercontent.com/7411300/149439940-3df738da-eaae-4b0b-a1a2-3f13e7158402.png)

最新版本已经1.22.0了

国内装不上可以，可以pip的时候用国内的镜像源，比如清华源，pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package
