### ISSUE TITLE
更换word中的数据后运行报错

### ISSUE THREAD

**Issue by Xu-xinxin** [delta-mpc/python-psi#5]
![591255e12fe4522907358e156b323cc](https://user-images.githubusercontent.com/55533248/155087786-ada46a2a-5609-4d9c-b019-cee18f092c0c.png)
![e4839fee8431abb9531ac2a9a6e41e6](https://user-images.githubusercontent.com/55533248/155087797-60a93f95-dc65-467d-af6c-7296515596cd.png)

我在运行delta-mpc时，更换word之后，运行会报以下错误，请问是什么原因，该如何解决呢

**Comment by mh739025250** [comment]
你好，我没有复现出这个问题。请问你是怎么操作的？

你可以新建一个新的虚拟环境，在虚拟环境里执行一下试试。

**Comment by Xu-xinxin** [comment]
当我跑原代码时可以正常运行。将两方的word部分都更改为range(1024)时也可以运行，改为range(2048)或者更大范围时会报上图的错，新建虚拟环境还是报相同的错。

**Comment by Xu-xinxin** [comment]
或者请问你们最大数据测到多少呢？谢谢你的解答~

**Comment by Xu-xinxin** [comment]
![image](https://user-images.githubusercontent.com/55533248/155138788-770c9fbd-4017-47a5-a06b-84c88a2ef347.png)
增加字节长度后我好像可以运行成功了，谢谢

**Comment by Xu-xinxin** [comment]
好像有时候还是会报错
![image](https://user-images.githubusercontent.com/55533248/155144247-da672736-f434-4313-ad69-66a4fafac67b.png)

**Comment by mh739025250** [comment]
Update the code to version 0.0.2. You can have a try.

**Comment by mh739025250** [comment]
Can you show your python version, os version and python packages?
