### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by Nlinnn** [delta-mpc/python-psi#6]
不知道如何解决
运行server或client都会报错
    from ..oprf import Client as OprfClient
ValueError: attempted relative import beyond top-level package

**Comment by mh739025250** [comment]
你是在哪个目录运行的，能给个截图吗

**Comment by feng002** [comment]
安装完库后将from ..oprf import Client as OprfClient 改为 from psi.oprf import Client as OprfClient 应该可以解决

**Comment by Nlinnn** [comment]
按照您说的修改后依旧有问题，是我的库安装错误了吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "delta-mpc/python-psi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [delta-mpc/python-psi] 运行不了 (Issue #6)





 
安装完库后将from ..oprf import Client as OprfClient 改为 from psi.oprf import Client as OprfClient 应该可以解决
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by feng002** [comment]
应该不是安装问题， 你可以试下这些代码：https://github.com/delta-mpc/python-psi/commit/ee98235723e974e6675141278c8cc85f47052a3a。
