### ISSUE TITLE
运行demo 代码出现错误

### ISSUE THREAD

**Issue by feng002** [delta-mpc/python-psi#7]
我在虚拟机里跑原代码demo命令的时候出现以下错误，请问应该如何解决？
![Capture](https://user-images.githubusercontent.com/59892828/155895854-e9e4b0ef-36cf-4299-863f-6fb0c2b95245.PNG)

**Comment by mh739025250** [comment]
可以提供一下你的python 版本，以及依赖包的版本吗？方便我这边复现一下。

**Comment by feng002** [comment]
![Capture](https://user-images.githubusercontent.com/59892828/155914277-0ff813f6-0ede-43ac-aa60-bb62b5fe91c2.PNG)
虚拟机用的Ubuntu-20.04

**Comment by mh739025250** [comment]
你python的版本是多少？
执行一下`python --version`

**Comment by feng002** [comment]
![Capture](https://user-images.githubusercontent.com/59892828/155914670-ded8bef0-2fd7-4e02-9277-7e22fb823e87.PNG)

**Comment by mh739025250** [comment]
在和你完全一样的环境下，还是无法复现你的问题

![4809c8a445bb4f0657a36d08384d3c2](https://user-images.githubusercontent.com/7411300/155937990-d249fef0-1de6-407f-ade7-1fb6054e3a33.png)


![23d7a01536c9d867994db2d1f4a4018](https://user-images.githubusercontent.com/7411300/155937998-b50fb412-a828-46b6-807d-e13af6111620.png)

**Comment by feng002** [comment]
![1](https://user-images.githubusercontent.com/59892828/156220539-9920ac40-ca4c-454c-b795-1fab239ec1e3.PNG)
![2](https://user-images.githubusercontent.com/59892828/156220544-83c47090-4685-4949-8008-fd91cabbe349.PNG)
我看了下应该是localhost不能在oprf server prepare 内稳定接收q_col(接收数据长度应该稳定在1505，但在实验中可能为0或者3010）, 请问下这应该怎么修复？

**Comment by Y0uth** [comment]
> 我在虚拟机里跑原代码demo命令的时候出现以下错误，请问应该如何解决？ ![Capture](https://user-images.githubusercontent.com/59892828/155895854-e9e4b0ef-36cf-4299-863f-6fb0c2b95245.PNG)

您好，我遇到了和您一样的问题，请问您解决了吗

**Comment by Y0uth** [comment]
![图片](https://user-images.githubusercontent.com/43675883/160592835-58adc723-bcc5-470e-bb17-b5484993d6d0.png)

**Comment by feng002** [comment]
> ![图片](https://user-images.githubusercontent.com/43675883/160592835-58adc723-bcc5-470e-bb17-b5484993d6d0.png)

我用的上个版本的代码，目前没有问题， 你可以试下这些代码（oprf_client.py, oprf_server.py, ote_sender.py, ote_reciever.py)：
https://github.com/delta-mpc/python-psi/commit/ee98235723e974e6675141278c8cc85f47052a3a?diff=unified%E3%80%82
