### ISSUE TITLE
目前的代码与之前版本的代码相比有什么进步的地方？

### ISSUE THREAD

**Issue by mrdutq** [delta-mpc/python-psi#8]
作者你好，我最近下载这个代码运行之后发现现在输入和输出都是在文本中，之前求交的数据是写在程序中的，这么做有什么好处？或者说，代码具体更新了哪些东西？（之前下载的代码找不到了。）与文献原作者开源的C++版本代码相比该代码有什么特点、优势？以上问题请大佬解答，谢谢。

**Comment by lencyforce** [comment]
This is not exactly an issue...
Please stop send issues like this...or ask such questions, it is not helping at all.
