### ISSUE TITLE
运行demo时报错

### ISSUE THREAD

**Issue by Y0uth** [delta-mpc/python-psi#9]
环境：Ubuntu20.04
python版本：3.8.10

1.pip intall .

![图片](https://user-images.githubusercontent.com/43675883/160608186-1f25fa51-6b49-4e8e-a77d-8597f3d35dfc.png)
![图片](https://user-images.githubusercontent.com/43675883/160608298-e4a3f86f-6197-4e32-8761-f5316c54f5eb.png)
因此按照提示添加环境变量
![图片](https://user-images.githubusercontent.com/43675883/160608548-56d27ad3-ec0f-47c5-b21c-c02d6eb8ee02.png)
![图片](https://user-images.githubusercontent.com/43675883/160608595-f6c15180-837f-49f4-a907-d8265f51e434.png)
![图片](https://user-images.githubusercontent.com/43675883/160609063-cd0ae476-aaf3-48e9-8881-418bc6b085c7.png)
报错

**Comment by kai-think-peach** [comment]
psi_run: command not found如何解决

**Comment by peachkk** [comment]
psi_run: command not found，How to solve it, what content to add to which file, can you tell me in detail?

**Comment by wywywyyyy** [comment]
psi_run: command not found，How to solve it, what content to add to which file, can you tell me in detail?
